/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author ai
 */
public class UIBarang extends javax.swing.JInternalFrame {
private entity.Barang b;
    /**
     * Creates new form UIBarang
     */
    public UIBarang(entity.Barang b) {
        this.b=b;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel kode = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        hrg = new javax.swing.JLabel();
        stok = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        kode.setText(b.getKode());
        kode.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));
        getContentPane().add(kode);

        nama.setText(b.getNm());
        nama.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 102, 255)));
        getContentPane().add(nama);

        hrg.setText(""+b.getHrg());
        hrg.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(hrg);

        stok.setText(""+b.getStok()+" "+b.getSatuan());
        stok.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 204)));
        getContentPane().add(stok);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hrg;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel stok;
    // End of variables declaration//GEN-END:variables
}
